version: '3'
services:
  db:
    image: 'postgres'
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: info
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server.info:
    image: node:alpine
    stdin_open: true
    container_name: server-info
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./:/server.info
      - /server.info/node_modules
    restart: always
    links:
      - db
